# Generated by Django 4.0.4 on 2022-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_iniciativa',
            field=models.BooleanField(default=False),
        ),
    ]
