# Generated by Django 4.0.4 on 2022-05-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0003_user_last_time_login_user_token_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
    ]
