# Generated by Django 4.0.4 on 2022-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0004_rename_password_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_time_login',
            field=models.DateTimeField(null=True),
        ),
    ]
